Update deploy-ecr.yaml

diff --git a/.github/workflows/deploy-ecr.yaml b/.github/workflows/deploy-ecr.yaml
--- a/.github/workflows/deploy-ecr.yaml
+++ b/.github/workflows/deploy-ecr.yaml
@@ -62,11 +62,19 @@ jobs:
         IMAGE_TAG="${{ github.event.inputs.tag }}"
         ENVIRONMENT="${{ github.event.inputs.environment }}"
           
+        # Get the workflow ID using the GitHub API
+        WORKFLOW_ID=$(curl -H "Authorization: token $TOKEN" -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows" | jq -r '.workflows[] | select(.name == "'$WORKFLOW_NAME'") | .id')
+        
+        if [ -z "$WORKFLOW_ID" ]; then
+          echo "Workflow not found"
+          exit 1
+        fi
+
         # Trigger the workflow using the GitHub API
         curl -X POST \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: token $TOKEN" \
-          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$(curl -H "Authorization: token $TOKEN" -s https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows | jq -r '.workflows[] | select(.name == "'$WORKFLOW_NAME'") | .id')/dispatches \
+          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_ID/dispatches" \
           -d "{\"ref\": \"main\", \"inputs\": { \"tag\": \"$IMAGE_TAG\", \"environment\": \"$ENVIRONMENT\" }}"
       env:
         GITHUB_API_TOKEN: ${{ secrets.P_GITHUB_API_TOKEN }}
